### ISSUE TITLE
System.NullReferenceException when scanning comments in v1.0.1270

### ISSUE THREAD

**Issue by arabcewicz** [sebastienros/esprima-dotnet#137]
The code
 ```csharp
    var scanner = new Scanner("var foo=1; /* \"330413500\" */", new ParserOptions {Comment = true, Loc = true});
    Token token;
    do
    {
        foreach (var comment in scanner.ScanComments())
            Console.WriteLine($"{comment.Start}-{comment.End}");
        token = scanner.Lex();
    } while (token.Type != TokenType.EOF);
 ```

works with Esprima v1.0.1258 (prints `11-28`) and doesn't work with v1.0.1270 where the exception is thrown:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Esprima.Scanner.SkipMultiLineComment() in C:\projects\esprima-dotnet\src\Esprima\Scanner.cs:line 317
   at Esprima.Scanner.ScanCommentsInternal() in C:\projects\esprima-dotnet\src\Esprima\Scanner.cs:line 425
   at Esprima.Scanner.ScanComments() in C:\projects\esprima-dotnet\src\Esprima\Scanner.cs:line 383
   at ConsoleApp1.Program.Main(String[] args) in C:\sandbox\EsprimaCheck\ConsoleApp1\Program.cs:line 15
```

**Comment by lahma** [comment]
Created https://github.com/sebastienros/esprima-dotnet/pull/138 to fix this issue.
