### ISSUE TITLE
Issue with parsing import statement

### ISSUE THREAD

**Issue by CharlieEriksen** [sebastienros/esprima-dotnet#403]
Webpack generates code like this:
```js
(self.webpackChunkcontainer = self.webpackChunkcontainer || []).push([
    [7767], {
        7767: (ae, H, l) => {
       
            function E() {
                return E = (0, h.Z)(function*(t, r) {
                    if ("string" == typeof t) return yield w(t, r);
                    if ("script" === t.type) {
                        const e = t;
                        return yield w(e.remoteEntry, e.remoteName)
                    }
                    "module" === t.type && (yield function J(t) {
                        return C.apply(this, arguments)
                    }(t.remoteEntry))
                }), E.apply(this, arguments)
            }

            function C() {
                return (C = (0, h.Z)(function*(t) {
                    return m[t] ? Promise.resolve() : yield import(t).then(r => {
                        T(r, t), m[t] = r
                    })
                })).apply(this, arguments)
            }

    
     
        }
    }
]);
```

This results in the following exception:
```
Esprima.ParserException: Line 20: Unexpected reserved word

Esprima.ParserException
Line 20: Unexpected reserved word
   at Esprima.JavaScriptParser.ThrowUnexpectedToken(Token& token, String message)
   at Esprima.JavaScriptParser.ConsumeSemicolon()
   at Esprima.JavaScriptParser.ParseReturnStatement()
   at Esprima.JavaScriptParser.ParseStatement()
   at Esprima.JavaScriptParser.ParseStatementListItem()
   at Esprima.JavaScriptParser.ParseFunctionSourceElements()
   at Esprima.JavaScriptParser.ParseFunctionExpression()
   at Esprima.JavaScriptParser.ParsePrimaryExpression()
   at Esprima.JsxParser.ParsePrimaryExpression()
   at Esprima.JavaScriptParser.ParseLeftHandSideExpressionAllowCall()
   at Esprima.JavaScriptParser.ParseUpdateExpression()
   at Esprima.JavaScriptParser.ParseUnaryExpression()
   at Esprima.JavaScriptParser.ParseBinaryExpressionOperand()
   at Esprima.JavaScriptParser.ParseBinaryExpression()
   at Esprima.JavaScriptParser.ParseAssignmentExpression()
   at Esprima.JavaScriptParser.IsolateCoverGrammar[T](Func`1 parseFunction)
   at Esprima.JavaScriptParser.ParseArguments()
   at Esprima.JavaScriptParser.ParseCallExpression(Boolean maybeAsync, Marker& startToken, Expression callee, Boolean optional)
   at Esprima.JavaScriptParser.ParseLeftHandSideExpressionAllowCall()
   at Esprima.JavaScriptParser.ParseUpdateExpression()
   at Esprima.JavaScriptParser.ParseUnaryExpression()
   at Esprima.JavaScriptParser.ParseBinaryExpressionOperand()
   at Esprima.JavaScriptParser.ParseBinaryExpression()
   at Esprima.JavaScriptParser.ParseAssignmentExpression()
   at Esprima.JavaScriptParser.IsolateCoverGrammar[T](Func`1 parseFunction)
   at Esprima.JavaScriptParser.ParseAssignmentExpression()
   at Esprima.JavaScriptParser.ParseGroupExpression()
   at Esprima.JavaScriptParser.ParsePrimaryExpression()
   at Esprima.JsxParser.ParsePrimaryExpression()
   at Esprima.JavaScriptParser.ParseLeftHandSideExpressionAllowCall()
   at Esprima.JavaScriptParser.ParseUpdateExpression()
   at Esprima.JavaScriptParser.ParseUnaryExpression()
   at Esprima.JavaScriptParser.ParseBinaryExpressionOperand()
   at Esprima.JavaScriptParser.ParseBinaryExpression()
   at Esprima.JavaScriptParser.ParseAssignmentExpression()
   at Esprima.JavaScriptParser.IsolateCoverGrammar[T](Func`1 parseFunction)
   at Esprima.JavaScriptParser.ParseExpression()
   at Esprima.JavaScriptParser.ParseReturnStatement()
   at Esprima.JavaScriptParser.ParseStatement()
   at Esprima.JavaScriptParser.ParseStatementListItem()
   at Esprima.JavaScriptParser.ParseFunctionSourceElements()
   at Esprima.JavaScriptParser.ParseFunctionDeclaration(Boolean identifierIsOptional)
   at Esprima.JavaScriptParser.ParseStatementListItem()
   at Esprima.JavaScriptParser.ParseFunctionSourceElements()
   at Esprima.JavaScriptParser.ParseAssignmentExpression()
   at Esprima.JavaScriptParser.ParseObjectProperty(Int32& protoCount)
   at Esprima.JavaScriptParser.ParseObjectInitializer()
   at Esprima.JavaScriptParser.ParsePrimaryExpression()
   at Esprima.JsxParser.ParsePrimaryExpression()
   at Esprima.JavaScriptParser.ParseLeftHandSideExpressionAllowCall()
   at Esprima.JavaScriptParser.ParseUpdateExpression()
   at Esprima.JavaScriptParser.ParseUnaryExpression()
   at Esprima.JavaScriptParser.ParseBinaryExpressionOperand()
   at Esprima.JavaScriptParser.ParseBinaryExpression()
   at Esprima.JavaScriptParser.ParseAssignmentExpression()
   at Esprima.JavaScriptParser.ParseArrayInitializer()
   at Esprima.JavaScriptParser.ParsePrimaryExpression()
   at Esprima.JsxParser.ParsePrimaryExpression()
   at Esprima.JavaScriptParser.ParseLeftHandSideExpressionAllowCall()
   at Esprima.JavaScriptParser.ParseUpdateExpression()
   at Esprima.JavaScriptParser.ParseUnaryExpression()
   at Esprima.JavaScriptParser.ParseBinaryExpressionOperand()
   at Esprima.JavaScriptParser.ParseBinaryExpression()
   at Esprima.JavaScriptParser.ParseAssignmentExpression()
   at Esprima.JavaScriptParser.IsolateCoverGrammar[T](Func`1 parseFunction)
   at Esprima.JavaScriptParser.ParseArguments()
   at Esprima.JavaScriptParser.ParseCallExpression(Boolean maybeAsync, Marker& startToken, Expression callee, Boolean optional)
   at Esprima.JavaScriptParser.ParseLeftHandSideExpressionAllowCall()
   at Esprima.JavaScriptParser.ParseUpdateExpression()
   at Esprima.JavaScriptParser.ParseUnaryExpression()
   at Esprima.JavaScriptParser.ParseBinaryExpressionOperand()
   at Esprima.JavaScriptParser.ParseBinaryExpression()
   at Esprima.JavaScriptParser.ParseAssignmentExpression()
   at Esprima.JavaScriptParser.IsolateCoverGrammar[T](Func`1 parseFunction)
   at Esprima.JavaScriptParser.ParseExpression()
   at Esprima.JavaScriptParser.ParseExpressionStatement()
   at Esprima.JavaScriptParser.ParseStatement()
   at Esprima.JavaScriptParser.ParseStatementListItem()
   at Esprima.JavaScriptParser.ParseModule(String code, String source)
```

Other JS parsers don't seem to dislike the code.

**Comment by adams85** [comment]
Yep, looks like a bug.

**Comment by adams85** [comment]
Do you need the fix released to NuGet ASAP or can you wait for v3.0 final, which is expected in a few days?

**Comment by CharlieEriksen** [comment]
No rush :)

**Comment by adams85** [comment]
Too late, v3 is out 😄
