### ISSUE TITLE
Error parsing empty JSX element

### ISSUE THREAD

**Issue by CharlieEriksen** [sebastienros/esprima-dotnet#407]
This would be valid JSX:

```jsx
var x = <></>;
```
However, the JSX parser doesn't like it:
```
Esprima.ParserException: Line 101: Unexpected token >
   at Esprima.JavaScriptParser.ThrowUnexpectedToken(Token& token, String message)
   at Esprima.JsxParser.ParseJsxIdentifier()
   at Esprima.JsxParser.ParseJsxElementName()
   at Esprima.JsxParser.ParseJsxBoundartElement()
   at Esprima.JsxParser.ParseComplexJsxElement(MetaJsxElement el)
   at Esprima.JsxParser.ParseJsxElement()
   at Esprima.JsxParser.ParseJsxRoot()
   at Esprima.JsxParser.ParsePrimaryExpression()
   at Esprima.JavaScriptParser.ParseLeftHandSideExpressionAllowCall()
   at Esprima.JavaScriptParser.ParseUpdateExpression()
   at Esprima.JavaScriptParser.ParseUnaryExpression()
   at Esprima.JavaScriptParser.ParseBinaryExpressionOperand()
   at Esprima.JavaScriptParser.ParseBinaryExpression()
   at Esprima.JavaScriptParser.ParseAssignmentExpression()
   at Esprima.JavaScriptParser.ParseGroupExpression()
   at Esprima.JavaScriptParser.ParsePrimaryExpression()
   at Esprima.JsxParser.ParsePrimaryExpression()
   at Esprima.JavaScriptParser.ParseLeftHandSideExpressionAllowCall()
   at Esprima.JavaScriptParser.ParseUpdateExpression()
   at Esprima.JavaScriptParser.ParseUnaryExpression()
   at Esprima.JavaScriptParser.ParseBinaryExpressionOperand()
   at Esprima.JavaScriptParser.ParseBinaryExpression()
   at Esprima.JavaScriptParser.ParseAssignmentExpression()
   at Esprima.JavaScriptParser.IsolateCoverGrammar[T](Func`1 parseFunction)
   at Esprima.JavaScriptParser.ParseExpression()
   at Esprima.JavaScriptParser.ParseReturnStatement()
   at Esprima.JavaScriptParser.ParseStatement()
   at Esprima.JavaScriptParser.ParseStatementListItem()
   at Esprima.JavaScriptParser.ParseFunctionSourceElements()
   at Esprima.JavaScriptParser.ParseAssignmentExpression()
   at Esprima.JavaScriptParser.IsolateCoverGrammar[T](Func`1 parseFunction)
   at Esprima.JavaScriptParser.ParseLexicalBinding(VariableDeclarationKind kind, Boolean inFor)
   at Esprima.JavaScriptParser.ParseBindingList(VariableDeclarationKind kind, Boolean inFor)
   at Esprima.JavaScriptParser.ParseLexicalDeclaration()
   at Esprima.JavaScriptParser.ParseStatementListItem()
   at Esprima.JavaScriptParser.ParseModule(String code, String source)
```

**Comment by adams85** [comment]
I can't reproduce this using the latest version (v3.0.0):

```cs
var parser = new JsxParser(new JsxParserOptions { Tolerant = false });
var root = parser.ParseScript("var x = <></>;");
Console.WriteLine(root.ToJavaScriptString(JavaScriptTextWriterOptions.Default, JsxAstToJavaScriptOptions.Default));
```

Even in non-tolerant mode it works fine on my side (tested on both .NET 5+ and .NET Framework).

Is there something I might be missing?

**Comment by CharlieEriksen** [comment]
You're right. I was still on the RC. It's not an issue in the final version :)
