### ISSUE TITLE
Issue with parsing spread operator

### ISSUE THREAD

**Issue by CharlieEriksen** [sebastienros/esprima-dotnet#416]
**Version used**

3.0.1

**Describe the bug**

I'm running into a case where the parser doesn't seem to like my spread operator. I've had a hell of a time trying to narrow spread operator issues down, as I've observed multiple. But they all appear to be non-trivial to reduce to a simple reproduction example. 

**To Reproduce**

```csharp

    [Fact]
    public void TestDotExport()
    {
        var javascriptCode = @"

export default [
  
].map((e, i) => ({
    ...e,
    index: i,
}));


";

        var parsed = new JavaScriptParser(new ParserOptions { Tolerant = true });
        var node = parsed.ParseModule(javascriptCode);
        node.Should().NotBeNull();
        var prettied = node.ToJavaScriptString(true);
        node = parsed.ParseModule(prettied);
        node.Should().NotBeNull();
    }
```

```
Line 5: Unexpected token .
   at Esprima.JavaScriptParser.ThrowUnexpectedToken(Token& token, String message)
   at Esprima.JavaScriptParser.ConsumeSemicolon()
   at Esprima.JavaScriptParser.ParseExportDeclaration()
   at Esprima.JavaScriptParser.ParseStatementListItem()
   at Esprima.JavaScriptParser.ParseModule(String code, String source)

```

**Expected behavior**
This should parse without issues.

**Comment by adams85** [comment]
@CharlieEriksen FYI, fixes for recent issues have been shipped with v3.0.2.
